dict_sites = {
'www.ankawa.com' : {'attr_type': 'h3' , 'attr_class':'class','attr_value':'catbg'},
'krmalk.tv' : {'attr_type': 'h1' , 'attr_class':'class','attr_value':'entry-title'},
'www.gdedak.tv' : {'attr_type': 'h1' , 'attr_class':'class','attr_value':'title_single'},
'shahid4u.tv' : {'attr_type': 'h2' , 'attr_class':'class','attr_value':'titleMovie'},
'www.4helal.tv' : {'attr_type': 'div' , 'attr_class':'class','attr_value':'bold'},
'aflamonlinee.online' : {'attr_type': 'h2' , 'attr_class':'class','attr_value':'titleMovie'},
'ramdan.video' : {'attr_type': 'h1' , 'attr_class':'class','attr_value':'entry-title'},
'cera.video' : {'attr_type': 'div' , 'attr_class':'class','attr_value':'breadCrumbs'},
'www.shahidwbas.com' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
'www.nsaem.net' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
'www.mzarita.tv' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
'www.rotana.video' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
'www.kolo.video' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
'qissat.video' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
'mosalsalaty.website' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
'www.bshwat.com' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
'www.emotionvideo-tv.com' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
'www.cimaspot.com' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
'www.mosalsalatlive.tv' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
'www.dardarkom.video' : {'attr_type': 'h1' , 'attr_class':'class','attr_value':'entry-title'},
'urcima.com' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
'cimaclub.com' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
'video.arab-x.com' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
'www.mosalslat.video' : {'attr_type': 'h1' , 'attr_class':'class','attr_value':'entry-title'},
'shamekh.video' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
'www.lahdat-news.com' : {'attr_type': 'div' , 'attr_class':'class','attr_value':'col-xs-12 col-sm-12 col-md-10'},
'www.shahid-online.net' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
'www.egyseries.com' : {'attr_type': 'h1' , 'attr_class':'class','attr_value':'entry-title'},
'dokan.news' : {'attr_type': 'h1' , 'attr_class':'class','attr_value':'entry-title'},
'www.123video.tv' : {'attr_type': 'h1' , 'attr_class':'class','attr_value':'entry-title'},
'www.s7efty.com' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
'cimaclub.online' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
'www.cimastars.com' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
'xn--ogbwbr6be.net' : {'attr_type': 'span' , 'attr_class':'itemprop','attr_value':'name'},
'www.taslyia.me' : {'attr_type': 'div' , 'attr_class':'class','attr_value':'col-xs-12 col-sm-12 col-md-10'},
'www.movizland.video' : {'attr_type': 'h1' , 'attr_class':'class','attr_value':'entry-title'},
'aflmelzem.video' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
'www.almlf.com' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
'www.cima4u.site' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
'elshra.online' : {'attr_type': 'h1' , 'attr_class':'class','attr_value':'entry-title'},
'www.almstba.tv' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
'www.halqat.tv' : {'attr_type': 'h1' , 'attr_class':'itemprop','attr_value':'name'},
}
